version: '3'
services:
  api:
    container_name: quizzical_dev_api
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 5000:5000
    environment: 
      - DB_NAME=quizzicaldb
      - DB_CONNECTION=mongodb://quizzical:quizzicalpass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"
  db:
    container_name: quizzical_dev_db
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=quizzical
      - MONGO_INITDB_DATABASE=quizzicaldb
      - MONGO_INITDB_ROOT_PASSWORD=quizzicalpass
volumes:
  dbdata: